'use strict';
const $=id=>document.getElementById(id);
let lines=[],layout=null,selected=-1,sourceBytes=null,sourceName='',zoom=1,revision=0,timer=null,paintScale=10;
const example='A：别出声，前面有人。\nB：你确定是这条路吗？\nA：看见那扇门了吗？\nA：等我发出信号，我们一起进去。\nB：明白。我数到三。\nB：一、二、三！\n';
function error(message){$('error').textContent=message||'';$('error').hidden=!message;}
function notice(message){$('notice').textContent=message||'';$('notice').hidden=!message;}
function interval(value){const n=Number(value);if(!Number.isFinite(n)||n<.1||n>600||Math.abs(n*10-Math.round(n*10))>1e-5)throw Error('间隔应为 0.1～600 秒，最多一位小数。');return Math.round(n*10);}
async function api(name,data,binary=false){const r=await fetch('api/'+name,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});if(!r.ok){let msg;try{msg=(await r.json()).error;}catch{msg=await r.text().catch(()=>r.statusText);}throw Error(msg||'操作失败');}return binary?r.blob():r.json();}
function request(){for(const input of document.querySelectorAll('#lines input')){if(!input.checkValidity())throw Error(input.getAttribute('aria-label')+'：'+(input.validationMessage||'请输入有效间隔'));}return {lines:lines.map(l=>({...l})),max_width:Number($('width').value),target:$('target').value.trim(),name:(sourceName||'dialogue').replace(/\.txt$/i,'').replace(/\.dialogue\.json$/i,'')};}
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),10000);}
function basename(){let name=(sourceName||'dialogue').replace(/\.(txt|dialogue\.json)$/i,'').replace(/[<>:"/\\|?*\u0000-\u001f]/g,'_').replace(/[. ]+$/,'').slice(0,80);if(!name||/^(con|prn|aux|nul|com[1-9]|lpt[1-9])$/i.test(name))name='dialogue_'+name;return name;}
function renderLines(){const body=$('lines');body.replaceChildren();$('empty').hidden=lines.length>0;$('linecount').textContent=lines.length+' 条';$('applydelay').disabled=!lines.length;$('saveproject').disabled=!lines.length;const fragment=document.createDocumentFragment();lines.forEach((line,i)=>{const tr=document.createElement('tr');tr.dataset.index=i;tr.classList.toggle('selected',i===selected);const num=document.createElement('td');num.textContent=line.source_line||i+1;const text=document.createElement('td');text.className='line-text';text.textContent=line.text||'（空行）';const delay=document.createElement('td'),count=document.createElement('td');count.className='repeat-number';if(i===lines.length-1){delay.textContent='末句';delay.className='muted';count.textContent='—';}else{const input=document.createElement('input');input.type='number';input.min='.1';input.max='600';input.step='.1';input.value=(line.delay_tenths/10).toFixed(1);input.setAttribute('aria-label','第 '+(i+1)+' 条后的间隔秒数');const caption=document.createElement('div');caption.className='after';caption.textContent='秒';delay.append(input,caption);count.textContent=Math.ceil(line.delay_tenths/4)+' 个';input.addEventListener('input',()=>{try{line.delay_tenths=interval(input.value);count.textContent=Math.ceil(line.delay_tenths/4)+' 个';input.setCustomValidity('');schedule();}catch(e){input.setCustomValidity(e.message);error('第 '+(i+1)+' 条：'+e.message);$('export').disabled=true;revision++;}});input.addEventListener('click',e=>e.stopPropagation());}tr.append(num,text,delay,count);tr.addEventListener('click',()=>selectLine(i,true));fragment.append(tr);});body.append(fragment);}
function selectLine(i,scroll){selected=i;document.querySelectorAll('#lines tr').forEach((r,n)=>r.classList.toggle('selected',n===i));draw();if(layout&&layout.events[i]){const e=layout.events[i];$('previewhint').textContent='第 '+(i+1)+' 条 · 相对坐标 '+e.x+', '+e.y+', '+e.z+' · 首句后 '+(e.at_tenths/10).toFixed(1)+' 秒';if(scroll)$('canvaswrap').scrollTo({top:Math.max(0,e.z*paintScale-90),behavior:'smooth'});}}
async function parseText(text,name){const parsed=await api('parse',{text,skip_blank:$('skipblank').checked,delay_tenths:interval($('defaultdelay').value)});lines=parsed.lines;selected=-1;sourceName=name;$('filename').textContent=name;$('filedetail').textContent=lines.length+' 条对白'+(parsed.blank_lines?' · '+($('skipblank').checked?'已忽略 ':'保留 ')+parsed.blank_lines+' 个空行':'');error('');notice('');renderLines();schedule(0);}
function decodeBytes(bytes){const v=new Uint8Array(bytes),choice=$('encoding').value;let encoding=choice;if(choice==='auto'){if(v[0]===255&&v[1]===254)encoding='utf-16le';else if(v[0]===254&&v[1]===255)encoding='utf-16be';else{try{return {text:new TextDecoder('utf-8',{fatal:true}).decode(v),encoding:'UTF-8'};}catch{encoding='gb18030';}}}return {text:new TextDecoder(encoding,{fatal:true}).decode(v),encoding:encoding.toUpperCase()};}
async function readFile(file){if(!file)return;if(file.size>4*1024*1024){error('TXT 文件最大为 4 MB。');return;}try{const bytes=await file.arrayBuffer();const decoded=decodeBytes(bytes);await parseText(decoded.text,file.name);sourceBytes=bytes;$('filedetail').textContent+=' · '+decoded.encoding;}catch(e){error('读取失败：'+e.message);}}
function schedule(delay=180){clearTimeout(timer);revision++;$('export').disabled=true;if(!lines.length)return;const rev=revision;timer=setTimeout(()=>updatePreview(rev),delay);}
async function updatePreview(rev){try{const result=await api('preview',request());if(rev!==revision)return;layout=result;error('');$('size').textContent=[result.width,result.length,result.height].join(' × ');$('repeatercount').textContent=result.repeaters.toLocaleString();$('duration').textContent=(result.duration_tenths/10).toFixed(1);$('rowcount').textContent=result.rows+' 排';$('export').disabled=false;$('exporthint').textContent=lines.length+' 个命令方块 · 导入后按金色方块上的按钮播放';draw();if(selected>=0)selectLine(selected,false);}catch(e){if(rev!==revision)return;layout=null;error(e.message);$('size').textContent=$('repeatercount').textContent=$('duration').textContent='—';$('export').disabled=true;draw();}}
function draw(){const canvas=$('canvas'),wrap=$('canvaswrap');$('previewempty').hidden=!!layout;if(!layout){canvas.width=1;canvas.height=1;return;}const ratio=Math.min(window.devicePixelRatio||1,2),available=wrap.clientWidth-34;let scale=Math.max(2,Math.min(20,available/layout.width))*zoom;scale=Math.min(scale,15000/layout.length);paintScale=scale;const w=Math.max(1,Math.ceil(layout.width*scale)),h=Math.max(1,Math.ceil(layout.length*scale));canvas.width=Math.ceil(w*ratio);canvas.height=Math.ceil(h*ratio);canvas.style.width=w+'px';canvas.style.height=h+'px';const ctx=canvas.getContext('2d');ctx.scale(ratio,ratio);ctx.fillStyle='#17251d';ctx.fillRect(0,0,w,h);if(scale>=5){ctx.strokeStyle='#283b2d';ctx.lineWidth=.4;ctx.beginPath();for(let x=0;x<=layout.width;x++){ctx.moveTo(x*scale,0);ctx.lineTo(x*scale,h);}for(let z=0;z<=layout.length;z++){ctx.moveTo(0,z*scale);ctx.lineTo(w,z*scale);}ctx.stroke();}const colors={button:'#e5ca73',dialogue:'#dfa163',repeater:'#d3766d',wire:'#815347'};for(const c of layout.cells){const x=c.x*scale,y=c.z*scale,pad=scale>5?1:0;ctx.fillStyle=colors[c.kind];ctx.fillRect(x+pad,y+pad,Math.max(.7,scale-2*pad),Math.max(.7,scale-2*pad));if(c.kind==='repeater'&&scale>=8){ctx.strokeStyle='#321d1b';ctx.lineWidth=1;const dx={east:1,west:-1,north:0,south:0}[c.facing],dy={east:0,west:0,north:-1,south:1}[c.facing],cx=x+scale/2,cy=y+scale/2;ctx.beginPath();ctx.moveTo(cx-dx*scale*.25,cy-dy*scale*.25);ctx.lineTo(cx+dx*scale*.25,cy+dy*scale*.25);ctx.lineTo(cx+dx*scale*.08-dy*scale*.14,cy+dy*scale*.08+dx*scale*.14);ctx.moveTo(cx+dx*scale*.25,cy+dy*scale*.25);ctx.lineTo(cx+dx*scale*.08+dy*scale*.14,cy+dy*scale*.08-dx*scale*.14);ctx.stroke();}if(c.kind==='dialogue'&&scale>=11){ctx.fillStyle='#2d2419';ctx.font=Math.max(7,scale*.51)+'px Segoe UI, sans-serif';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(c.line,x+scale/2,y+scale/2);}}if(selected>=0&&layout.events[selected]){const e=layout.events[selected];ctx.strokeStyle='#ebfbdc';ctx.lineWidth=2;ctx.strokeRect(e.x*scale-2,e.z*scale-2,scale+4,scale+4);}}
$('txtfile').addEventListener('change',e=>readFile(e.target.files[0]));
$('example').addEventListener('click',async()=>{try{sourceBytes=null;await parseText(example,'示例剧情.txt');}catch(e){error(e.message);}});
for(const event of ['dragenter','dragover'])$('dropzone').addEventListener(event,e=>{e.preventDefault();$('dropzone').classList.add('drag-over');});
for(const event of ['dragleave','drop'])$('dropzone').addEventListener(event,e=>{e.preventDefault();$('dropzone').classList.remove('drag-over');if(event==='drop')readFile(e.dataTransfer.files[0]);});
async function reparse(){if(!sourceBytes)return;try{const name=sourceName,decoded=decodeBytes(sourceBytes);await parseText(decoded.text,name);notice('已重新读取 TXT，逐句间隔已恢复为默认值。');}catch(e){error(e.message);}}
$('encoding').addEventListener('change',reparse);$('skipblank').addEventListener('change',reparse);
$('applydelay').addEventListener('click',()=>{try{const n=interval($('defaultdelay').value);lines.forEach(l=>l.delay_tenths=n);renderLines();schedule(0);}catch(e){error(e.message);}});
$('width').addEventListener('input',()=>schedule());$('target').addEventListener('input',()=>schedule());
$('zoomout').addEventListener('click',()=>{zoom=Math.max(.3,zoom/1.3);draw();});$('zoomin').addEventListener('click',()=>{zoom=Math.min(4,zoom*1.3);draw();});$('zoomreset').addEventListener('click',()=>{zoom=1;draw();});
$('canvas').addEventListener('click',e=>{if(!layout)return;const rect=e.currentTarget.getBoundingClientRect(),x=Math.floor((e.clientX-rect.left)/paintScale),z=Math.floor((e.clientY-rect.top)/paintScale),i=layout.events.findIndex(p=>p.x===x&&p.z===z);if(i>=0){selectLine(i,false);$('lines').children[i].scrollIntoView({block:'nearest',behavior:'smooth'});}});
$('export').addEventListener('click',async()=>{const rev=revision;try{$('export').disabled=true;const data=request(),blob=await api('export',data,true);download(blob,basename()+'.schem');notice('结构文件已生成。浏览器将保存 .schem 文件；可用“保存设置”保留逐句间隔。');}catch(e){error(e.message);}finally{if(rev===revision)$('export').disabled=!layout||!!document.querySelector('#lines input:invalid');}});
$('saveproject').addEventListener('click',()=>{try{download(new Blob([JSON.stringify(request(),null,2)],{type:'application/json'}),basename()+'.dialogue.json');}catch(e){error(e.message);}});
$('projectfile').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>8*1024*1024)throw Error('项目文件过大');const data=JSON.parse(await file.text());const validated=await api('preview',data);lines=data.lines;sourceName=(data.name||file.name)+'.txt';sourceBytes=null;$('width').value=data.max_width;$('target').value=data.target;$('filename').textContent=sourceName;$('filedetail').textContent='已载入 '+lines.length+' 条对白和逐句间隔';selected=-1;layout=validated;renderLines();schedule(0);notice('项目设置已载入。');}catch(e){error('载入失败：'+e.message);}});
$('quit').addEventListener('click',async()=>{if(lines.length&&!confirm('退出后，未保存的逐句设置将丢失。确定退出软件吗？'))return;try{await api('shutdown',{});document.querySelector('.workspace').classList.add('offline');$('quit').disabled=true;notice('软件已退出，现在可以关闭本页。');}catch(e){error(e.message);}});
new ResizeObserver(()=>draw()).observe($('canvaswrap'));
